### ISSUE TITLE
Thornbot - Verify

### ISSUE THREAD

**Issue by HeadSh4t** [CasualCadeDK/CasualCade#46]
Thornbot verify på discorden
Når nye mennesker joiner discorden er den samme
Gamle besked der, & da vi lukket thornbot ned fungere
Dette system ikke, tænker generalt selv vi skal have et nyt
Et med den nye bot ^^

**Comment by Mwthorn** [comment]
Jeg har næsten det nye system klar. Har dog ikke lige haft tid til at sætte det helt op endnu.

Indtil videre må man lige skrive privat til mig eller ItzzAmazing for at gøre det manuelt.

**Comment by Mwthorn** [comment]
Problemet burde være løst nu med den nye Thornbot
