### ISSUE TITLE
Fejl i Skilte

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#55]
Fejl når man prøver bruge skilte ved højre klikke på dem.. det sker for disse forskelige ting
-Plot kits
-Plot buff

tror det sker ved de forskelige plot relateret skilte ting altså man kan ikke højre klikke på skiltet også får man buff/kittet

**Comment by Mwthorn** [comment]
Det er for det meste fikset nu, mangler lige [Copy] men det tilhører under #59
