### ISSUE TITLE
Copy gennem verdener

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#75]
Jeg går ud fra det en fejl at du ikke kan copy ting fra en verden til en anden da man før i tiden har kunne gøre det jeg vil bare gøre opmærksom på at man ikke kan gøre det pt :)

**Comment by HeadSh4t** [comment]
Dette skyldes vel pw systemet, samt generalt verden system, kan ikke selv lige se hvordan dette kan løses, men du kunne altid lave en schematic og sætte den ind i den anden verden
