### ISSUE TITLE
Sælge kiste forslag

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#79]
Okay Jeg har nogle forslag vedrøende den sælge kiste man kan setup på sit plot lige nu :slight_smile: da lige nu er der intet der giver penge i den går jeg ud fra det fordi i mangler forslag til hvad ting skal have af værdi!
nå men her min liste med hvad ting burte sælges for dette er bare generalt standard prison ting!
-Diamond Sword -300
DIamond boots: -650
Diamond leggings -850
Diamond chestplate - 1000
Diamond helmet 450
Stone pickaxe -1.5
Iron pickaxe -3
Iron helmet -225
Iron Chestplate -500
Iron leggings -425
Iron Boots -325
Iron Sword -150
Bread -500
wheat -150
Wheat_Seeds -25
Blaze rod -175
Stone Axe -10
Iron Axe -15
Cobblestone -1
Stone 1.5
Dette er bare mit forslag til hvad det skal kunne give sælge dette er de primere prison items :)
EXTRA FORSLAG: Gøre så man kan setup flere end bare 1 sælgekiste på ets plot måske 3-5 med supercc :)

**Comment by Mwthorn** [comment]
Dupe af #7
