### ISSUE TITLE
Flere plot portaler?

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#81]
Nu ved jeg godt i har gjort så man kunne have flere plot portaler 1 gang men kan i gøre så man kan lave flere igen?...

**Comment by HeadSh4t** [comment]
Støtter dig fuldstændig omkring dine forslag men, serveren
Kan ikke blive ved med at lave ting til bare dig, forstår fuldstændig at
Du skal bruge dem til dit "prisonplot" men igen, tænker personligt ikke mange vil
Bruge alle disse ting du har lavet forslag om, men igen bare en tanke :).

**Comment by Mwthorn** [comment]
@HeadSh4t Det kan give andre inspiration til at lave noget hvor man ikke lader sig begrænse af hvad der nuværende er adgang til. Videre diskussion omkring dette ville nok kræve en ny issue specifikt omkring at lave ting til kun en spiller.

Der er lavet følgene ændringer på maks antal plotportaler per plot:
Normal adgang: 1 -> 4
SuperCC adgang: 10 -> 30
