### ISSUE TITLE
Buffs af Crates

### ISSUE THREAD

**Issue by badensoe** [CasualCadeDK/CasualCade#84]
På Bare_Mathias's Plot er cratesne mega dårlige og de giver egenligt ikke rigtigt nogle penge. Har fået afvide at det ikke er fra plot til plot men er noget Som CC styrer. Ville det være muligt at kunne give en mulighed at man individuelt kan buffe/nerfe eller bare hæve profitsne

**Comment by Mwthorn** [comment]
Det er lidt det samme af hvad custom crates ville løse #3
