### ISSUE TITLE
Celle Skilt 

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#88]
Fejl når du opretter celle skilt ved ikke om det kan ses men jeg kigger altså helt inde i skiltet XD
Nå men tænker det en fejl u plot merge idk!
![image](https://user-images.githubusercontent.com/52397284/97987155-1b6b6b00-1ddb-11eb-9099-00be943dd73f.png)

**Comment by Mwthorn** [comment]
Det er rettet nu
