### ISSUE TITLE
Regions fejl

### ISSUE THREAD

**Issue by BareGGMathias** [CasualCadeDK/CasualCade#89]
![image](https://user-images.githubusercontent.com/52397284/98444289-1bd47080-2111-11eb-9e58-4c6ad668c9f8.png)
Som man kan se på billedet kan jeg ikke få lov oprette en no-pvp zone :)

**Comment by BareGGMathias** [comment]
tilføjelse det skal siges at det kun sker i få områder

**Comment by BareGGMathias** [comment]
Kun i merget plots

**Comment by Mwthorn** [comment]
Rettet region checks på Celler, PlotPortaler & Non-PvP Zoner.
