### ISSUE TITLE
Auto-ban VPN. 

### ISSUE THREAD

**Issue by Congraz8961** [CasualCadeDK/CasualCade#97]
Hej Casualcade

Jeg kom direkte fra min egen server, hvor jeg var ved at teste mit antivpn plugin, og havde glemt at tage det af. Så jeg kom til at joine Casualcade med den på, og fik direkte et auto-ban (vpn) (M247). Det skete helt tilbage til den 23/12 2020. Ret langtid siden, og har først opdaget det nu... Jeg har aldrig fået ban fra jeres server før. (tjek gerne ban-history). 

Håber jeg kan få et unban, og bygge videre på nogle af mine projekter ;)

Bruger jeg spiller på Casualcade med: ThqBeqr og Congraz

**Comment by Mwthorn** [comment]
Jeg har unbanned begge dine brugere og whitelisted dem så du kan join med VPN uden bekymring.
