### ISSUE TITLE
Hvordan ban appealer jeg?

### ISSUE THREAD

**Issue by BigTastyLakrids** [CasualCadeDK/CasualCade#98]
Så jeg blev Perm bannet for at bruge en VPN fordi jeg ikke vidste det var banable og jeg har kigget rundt og jeg kan bare ikke finde hvor man skriver et ban appeal?

**Comment by Mwthorn** [comment]
Det fint nok at skrive her. Hvad er dit ign (In-game name)?

**Comment by BigTastyLakrids** [comment]
> Det fint nok at skrive her. Hvad er dit ign (In-game name)?

Mit ign er Bigtastylakrids

**Comment by Mwthorn** [comment]
Jeg har unbanned og whitelisted dig nu så du kan bruge VPN :)
