### ISSUE TITLE
Unban Appeal

### ISSUE THREAD

**Issue by Magnus360j** [CasualCadeDK/CasualCade#99]
Hejsa. Jeg fik perm ban for at sidde på vpn, som jeg ikke vidste.
Bruger nordvpn til netflix, og var også koblet af men da jeg joinede blev jeg perm bannet, og så ser jeg den stadig er aktiv.
Vil bare gerne have unban, da jeg elsker at bygge designs.

Navn: TheFlashCW

**Comment by Mwthorn** [comment]
Jeg har unbanned og whitelisted dig nu så du kan bruge VPN :)
